title: Aritra Bhattacharyya
logo: "aritra.png?raw=true"
description: >
  Front-end Developer | MarTech Consultant
  <br/>
  <a href="mailto:aribhatt91@gmail.com">aribhatt91@gmail.com</a>
  <br/>
  <a href="https://www.linkedin.com/in/aribhatt/">LinkedIn</a>
  <br/>
  <a href="https://github.com/aribhatt91/">GitHub</a>
theme: jekyll-theme-minimal
